name 'chef-spike-crontab-crond-debian'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures chef-spike-crontab-crond-debian'
long_description 'Installs/Configures chef-spike-crontab-crond-debian'
issues_url 'https://github.com'
source_url 'https://github.com/pellekrogholt/chef-spike-crontab-crond-debian'
version '0.1.0'
